== Support for Jackson

Jackson is very customizable, but Apina supports only a small statically analyzable subset of Jackson. If
you have customized Jackson mappings heavily in the global configuration, it's unlikely that Apina will pick
up your customizations. Same is true if you have used some of Jackson's more exotic annotations.

Mostly the translation is pretty unsurprising: Apina traverses fields and properties the same way that Jackson
would do and creates matching TypeScript interfaces. However, there are a few things to know:

=== Enums

On the wire, enumerations are always represented by their literal name, but there are three different ways that they
can be represented in TypeScript. These can be controlled by setting the `enumMode` property of the Gradle plugin.

So, for following enum:

[source,kotlin]
----
enum class Toggle {
    ON | OFF
}
----

the possible translations would be:

.Enum translations
[cols="2,5"]
|===
|Enum-mode|Generated code

|`DEFAULT`
|`enum Toggle { ON = "ON", OFF = "OFF" }`

|`INT_ENUM`
|`enum Toggle { ON, OFF }`

|`STRING_UNION`
|`type Toggle = "ON" \| "OFF"`
|===

Generally you should use the `DEFAULT` mode if you don't have a really good reason to do otherwise.

=== Flattening

Apina will look for properties in superclasses, but will flatten the result into a single TypeScript interface. So:

[source,kotlin]
----
open class Event {
    val timestamp = Instant.now()
}

class LoginEvent(val username: String) : Event()
----

will turn into:

[source,typescript]
----
interface LoginEvent {
    timestamp: Instant
    username: String
}
----

First of all, TypeScript is structurally typed so supertypes are not really necessary. And second, keeping
the supertype name available is useful when using _discriminated unions_:

=== Discriminated unions

Apina supports mapping Jackson's sub types into TypeScript's
https://www.typescriptlang.org/docs/handbook/advanced-types.html#discriminated-unions[discriminated unions] as long
as you use `@JsonTypeInfo` with `use=NAME` and specify property name for discriminator. Moreover, you must list
the sub-types and define their discriminator values explicitly:

[source,kotlin]
----
@JsonTypeInfo(use=NAME, property="type")
@JsonSubTypes(
    Type(value = Bar::class, name = "my_bar"),
    Type(value = Baz::class, name = "my_baz")
)
abstract class Foo { ... }

class Bar : Foo() { ... }

class Baz : Foo() { ... }
----

This creates interfaces normally for `Bar` and `Baz` and then adds the following types:

[source,typescript]
----
export interface Foo_Bar extends Bar {
    type: "my_bar";
}

export interface Foo_Baz extends Baz {
    type: "my_baz";
}

export type Foo = Foo_Bar | Foo_Baz;
----

This way you can easily pass heterogeneous data back and forth between client and server.

==== Kotlin sealed classes

With Java, you must use `@JsonSubTypes` to find the subtypes of a class, but when using
Kotlin and sealed classes, you don't need it. However, you need to use `@JsonTypeName`
to specify names for the types:

[source,kotlin]
----
@JsonTypeInfo(use=NAME, property="type")
sealed class Foo { ... }

@JsonTypeName("my_bar")
class Bar : Foo() { ... }

@JsonTypeName("my_baz")
class Baz : Foo() { ... }
----

=== Supported annotations

That said, straightforward Jackson mappings should generally work without hassle. Most of the time you don't
need any annotations. When you need to control the mappings, following Jackson annotations are recognized
by Apina as well:

.Supported Jackson annotations:
[cols="2,5"]
|===
|Annotation |Description

|`@JsonIgnore`
|Property is ignored

|`@JsonValue`
|Properties of the owning class will be ignored and the return type of the annotated method will be
used as its representation.

|`@JsonUnwrapped`
|Properties of the target class will be inlined into the referencing class.

|`@JsonTypeInfo`, `@JsonSubTypes`, `@JsonTypeName`
|Class will be translated into a _discriminated union_.
|===

Finally, `java.beans.Transient` can be used as to ignore a property as well.

Other annotations are not supported at the moment.
