== Customization type mappings

While most of the time Apina does the right thing without additional configuration,
sometimes you need to have more control over either the build time translation or
runtime execution.

Normally when Apina sees a referenced class, it will analyze its properties and fields
decide how it should be serialized: just like Jackson does. However, for some types
this makes no sense.

As an example, perhaps you don't want `java.time.Instant` to be serialized as
`{ "seconds": 1550778425, "nanos": 398000000" }` but would prefer it to be represented
as `"2019-02-21T19:47:05.398Z"` on the wire. And instead of handling it as a `string`
in TypeScript, you'd probably want it to be converted to `Date` or perhaps
https://js-joda.github.io/js-joda/[js-joda]'s `Instant`. Apina can do both of these.

=== Configuring translation

First we'll configure the Gradle task to _import_ `Instant` from another file instead
of trying to translate it:

[source,kotlin]
----
apina {
    ...
    imports = mapOf("./my-apina-types" to listOf("Instant"))
}
----

Now whenever Apina sees the type `Instant` (Apina ignores package names) it won't try to
generate code for it, but assume that the user has provided it. Furthermore it adds the
code `import { Instant } from "./my-apina-types";` on top of the generated file.

Next, we'll write `my-apina-types.ts`. For our example, we'll use JavaScript's `Date`
for representation of `Instant`, so we'll simply specify a type alias:

[source,typescript]
----
export type Instant = Date;
----

=== Configuring runtime serialization

Next we'll need to instruct Apina to customize the serialization format used on JavaScript. (Of
course you also need to configure Jackson similarly, but that's out of scope for this document.)
Apina generates an `ApinaConfig` class whose default constructor will configure all serializers
that Apina can deduce itself. Therefore we can just construct the default instance and then
customize it by registering our own serializer for instants:

[source,typescript]
----
export function createApinaConfig(): ApinaConfig {
    const config = new ApinaConfig();

    config.registerSerializer("Instant", {
        serialize(o) { return formatISO8601(o); },
        deserialize(o) { return parseISO8601(o); }
    });

    return config;
}
----

Finally we'll register `createApinaConfig` as a factory for `ApinaConfig` in our Angular module:

[source,typescript]
----
@NgModule({
    ...
    providers: [
        { provide: ApinaConfig, useFactory: createApinaConfig }
    ]
})
export class MyModule { }
----

TIP: When generating code for ES6, you won't register the provider for Angular, but you'll
simply pass configuration as a constructor parameter when instantiating endpoint-classes.
