== Customizing HTTP requests

=== Override request handling

Sometimes you need more control over the HTTP requests Apina makes. Perhaps
you are behind a proxy and need to mangle the URL somehow or perhaps you'll want
to add some headers to requests.

You can implement these by implementing replacing Apina's `ApinaEndpointContext`
with your own. When Apina generates code for endpoints, it actually just builds
a structure representing the details of the request and passes it to endpoint
context for actual execution:

[source,typescript]
----
findOrders(customerId: number): Observable<Order> {
    return this.context.request({
        'uriTemplate': '/api/customer/{customerId}/orders',
        'method': 'GET',
        'pathVariables': {
            'customerId': this.context.serialize(customerId, 'number')
        },
        'responseType': 'Order'
    });
}
----

Therefore, you can easily implement your own endpoint context that does something
different than the default one:

[source,typescript]
----
@Injectable()
export class MyApinaEndpointContext extends ApinaEndpointContext {

    constructor(config: ApinaConfig) {
        super(config);
    }

    request(data: RequestData): Observable<any> {
        ... do something completely different ...
    }
}
----

Finally, register it so that Apina uses it:

[source,typescript]
----
@NgModule({
    ...
    providers: [
        { provide: ApinaEndpointContext, useClass: MyApinaEndpointContext }
    ]
})
export class MyModule { }
----

TIP: When targeting ES6, you can just instantiate your own context normally and
pass it to constructor of your endpoint class.

TIP: When targeting Angular, Apina's `DefaultApinaEndpointContext` uses Angular's
`HttpClient` to execute the requests. Therefore things like authorization headers
are probably best implemented as interceptors for `HttpClient` instead of writing an
Apina-specific implementation. Custom endpoint context can still be useful for
some cases which need higher-level knowledge of the requests.

=== Build URLs without requests

It's also possible to configure Apina to build methods that simply return the
request URL without making a request. This could be used for a strongly typed
download link or performing really exotic requests while still getting help
from Apina.

Suppose we have following controller:

[source,kotlin]
----
package example

@RestController
class DownloadController {

    @GetMapping("/download/{name}")
    fun download(@PathVariable name: String, @RequestParam code: Int): Document {
        ...
    }
}
----

We can now configure a regex matching to the fully qualified name of the method to
tell Apina that we want URL-generation for this method:

[source,kotlin]
----
tasks.apina {
    endpointUrlMethods = listOf("""hello\.DownloadController\.download""")
}
----

Now Apina creates two methods instead of one. First you can use to call the endpoint
as normally, whereas you can use one with `Url`-suffix to create the URL:

[source,typescript]
----
interface DownloadEndpoint {
    download(name: String, code: Int): Observable<Document>;
    downloadUrl(name: String, code: Int): string;
}
----

Methods with `@RequestBody` parameter are supported, but they are omitted from the
URL-method, since it's impossible to create a URL with request body. In that case,
you need to  pass the body manually when you end up calling the URL.
